version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn socialworkoutapi.main:app --port=96 --host=0.0.0.0"
    container_name: socialworkout-api
    env_file:
      - .env
    networks:
      - nginxproxymanager_default
    ports:
      - 5002:96

networks:
  nginxproxymanager_default:
    external: true
